### ISSUE TITLE
Grammar fixes

### ISSUE THREAD

**Issue by Fixer-007** [tacigar/minetest-digall#13]
Noticed this part, which is confusing:
![default](https://user-images.githubusercontent.com/16494741/33800797-b7f1b2aa-dd50-11e7-8dd5-e03e61942884.png)

Should be:
Enable -> Enabled
Disable -> Disabled

Same for:
![default](https://user-images.githubusercontent.com/16494741/33800829-a20f3650-dd51-11e7-898e-b1e12912124c.png)

Should be:
Activate -> Activated
Deactivate -> Deactivated

**Comment by tacigar** [comment]
Thanks :)
