### ISSUE TITLE
Organise the mod a little bit

### ISSUE THREAD

**Issue by Fixer-007** [tacigar/minetest-digall#7]
Please add following files to distribution:
* mod.conf
* depends.txt
* description.txt

You can look up examples from others mods (this one for example: https://github.com/tenplus1/protector), details here too https://rubenwardy.com/minetest_modding_book/lua_api.html#mod-directory-structure and on wiki probably.

**Comment by tacigar** [comment]
@Fixer-007 
Thanks for your advice :)
Are `mod.conf` and `depends.txt` absolutely necessary?
This mod doesn't depend on other mods.

**Comment by Fixer-007** [comment]
proper mod.conf should fix those folder naming errors, not sure about depends.txt, it is not necessary, but at least put mod.conf
