### ISSUE TITLE
Singleplayer/Serverplayer can digall without priv

### ISSUE THREAD

**Issue by Fixer-007** [tacigar/minetest-digall#9]
Please also check simple player on actual server, I suspect problems, but can't check due to https://github.com/tacigar/minetest-digall/issues/8

Minetest 0.5.0-c0dd4ea4

**Comment by tacigar** [comment]
I'm sorry, I don't know much about minetest-server.
I'll try to run a local server and check it.

**Comment by Fixer-007** [comment]
I mean the one you start via "Local Game" with "server" checked. This way you pretty much play the game while opening to other players.

**Comment by tacigar** [comment]
Fixed.
Please use it.
